// This file was generated by Gemini AI
//
// gcc -O3 ntp-diff.c -o ntp-diff
// ./ntp-diff 192.168.40.190 time.nist.gov 5

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <netdb.h>
#include <stdint.h>
#include <time.h>
#include <math.h>
#include <signal.h> // Added for Ctrl+C handler

#define NTP_PORT "123"
#define NTP_PACKET_SIZE 48
#define NTP_TO_UNIX_EPOCH 2208988800ULL
#define NTP_VERSION 4
#define NTP_MODE_CLIENT 3
#define NTP_MODE_SERVER 4
#define NTP_FRACTION_SCALE 4294967296.0
#define PROBES_PER_HOST 3
#define PROBE_GAP_US 20000

// Global metrics for the Ctrl+C Final Summary
volatile sig_atomic_t keep_running = 1;
int global_valid_samples = 0;
double global_sum_drift = 0.0;
double global_sum_jitter_dev = 0.0;
const char *global_sample_host = NULL;
const char *global_ref_host = NULL;

struct ntp_packet {
    uint8_t li_vn_mode;      
    uint8_t stratum;         
    uint8_t poll;            
    uint8_t precision;       
    uint32_t rootDelay;      
    uint32_t rootDispersion; 
    uint32_t refId;          
    uint32_t refTm_s;        
    uint32_t refTm_f;        
    uint32_t origTm_s;       
    uint32_t origTm_f;       
    uint32_t rxTm_s;         
    uint32_t rxTm_f;         
    uint32_t txTm_s;         
    uint32_t txTm_f;         
};

typedef struct {
    double offset_s;
    double delay_s;
} ntp_sample_t;

// Signal Interrupt Handler
void handle_sigint(int sig) {
    (void)sig;
    keep_running = 0;
}

// DNS Resolution
int resolve_dns(const char *host, struct sockaddr_in *out_addr) {
    struct addrinfo hints, *res;
    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;       
    hints.ai_socktype = SOCK_DGRAM;  

    int status = getaddrinfo(host, NTP_PORT, &hints, &res);
    if (status != 0) {
        fprintf(stderr, "DNS Error for '%s': %s\n", host, gai_strerror(status));
        return -1;
    }
    memcpy(out_addr, res->ai_addr, sizeof(struct sockaddr_in));
    freeaddrinfo(res);
    return 0;
}

static double timespec_to_unix_seconds(const struct timespec *ts) {
    return (double)ts->tv_sec + ((double)ts->tv_nsec / 1000000000.0);
}

static double ntp_to_unix_seconds(uint32_t ntp_seconds, uint32_t ntp_fraction) {
    int64_t unix_seconds = (int64_t)ntp_seconds - NTP_TO_UNIX_EPOCH;
    double frac_seconds = (double)ntp_fraction / NTP_FRACTION_SCALE;
    return (double)unix_seconds + frac_seconds;
}

// Single NTP transaction using full 4-timestamp offset/delay equations.
static int query_ntp_once(int sock_fd, const struct sockaddr_in *target_addr, ntp_sample_t *out_sample) {
    struct ntp_packet packet;
    struct sockaddr_in recv_addr;
    struct timespec t1, t4;
    socklen_t addr_len = sizeof(recv_addr);

    uint32_t t1_ntp_sec;
    uint32_t t1_ntp_frac;

    memset(&packet, 0, sizeof(packet));
    packet.li_vn_mode = (uint8_t)((NTP_VERSION << 3) | NTP_MODE_CLIENT);

    if (clock_gettime(CLOCK_REALTIME, &t1) != 0) {
        return -1;
    }

    t1_ntp_sec = (uint32_t)((uint64_t)t1.tv_sec + NTP_TO_UNIX_EPOCH);
    t1_ntp_frac = (uint32_t)(((uint64_t)t1.tv_nsec << 32) / 1000000000ULL);
    packet.txTm_s = htonl(t1_ntp_sec);
    packet.txTm_f = htonl(t1_ntp_frac);

    if (sendto(sock_fd, &packet, NTP_PACKET_SIZE, 0, (const struct sockaddr *)target_addr, addr_len) < 0) {
        return -1;
    }

    ssize_t recv_len = recvfrom(sock_fd, &packet, NTP_PACKET_SIZE, 0, (struct sockaddr *)&recv_addr, &addr_len);
    if (recv_len != NTP_PACKET_SIZE) {
        return -1;
    }

    if (clock_gettime(CLOCK_REALTIME, &t4) != 0) {
        return -1;
    }

    // Reject packets from a different host/port.
    if (recv_addr.sin_addr.s_addr != target_addr->sin_addr.s_addr || recv_addr.sin_port != target_addr->sin_port) {
        return -1;
    }

    uint8_t mode = (uint8_t)(packet.li_vn_mode & 0x7);
    if (mode != NTP_MODE_SERVER) {
        return -1;
    }

    // Origin timestamp must echo our request's transmit timestamp.
    uint32_t orig_sec = ntohl(packet.origTm_s);
    uint32_t orig_frac = ntohl(packet.origTm_f);
    if (orig_sec != t1_ntp_sec || orig_frac != t1_ntp_frac) {
        return -1;
    }

    uint32_t rx_sec = ntohl(packet.rxTm_s);
    uint32_t rx_frac = ntohl(packet.rxTm_f);
    uint32_t tx_sec = ntohl(packet.txTm_s);
    uint32_t tx_frac = ntohl(packet.txTm_f);

    double t1_s = timespec_to_unix_seconds(&t1);
    double t2_s = ntp_to_unix_seconds(rx_sec, rx_frac);
    double t3_s = ntp_to_unix_seconds(tx_sec, tx_frac);
    double t4_s = timespec_to_unix_seconds(&t4);

    double offset = ((t2_s - t1_s) + (t3_s - t4_s)) / 2.0;
    double delay = (t4_s - t1_s) - (t3_s - t2_s);
    if (delay < 0.0) {
        delay = 0.0;
    }

    out_sample->offset_s = offset;
    out_sample->delay_s = delay;
    return 0;
}

// Multi-probe query: pick the sample with minimum delay for better accuracy.
int get_ntp_offset_seconds(int sock_fd, const struct sockaddr_in *target_addr, double *out_offset, double *out_delay) {
    ntp_sample_t best = {0.0, 0.0};
    int got_sample = 0;

    for (int i = 0; i < PROBES_PER_HOST && keep_running; i++) {
        ntp_sample_t sample;
        if (query_ntp_once(sock_fd, target_addr, &sample) == 0) {
            if (!got_sample || sample.delay_s < best.delay_s) {
                best = sample;
                got_sample = 1;
            }
        }

        if (i + 1 < PROBES_PER_HOST && keep_running) {
            usleep(PROBE_GAP_US);
        }
    }

    if (!got_sample) {
        return -1;
    }

    *out_offset = best.offset_s;
    if (out_delay != NULL) {
        *out_delay = best.delay_s;
    }
    return 0;
}

int main(int argc, char *argv[]) {
    if (argc != 4) {
        fprintf(stderr, "Usage: %s <sample_server> <reference_server> <num_samples>\n", argv[0]);
        return EXIT_FAILURE;
    }

    const char *sample_host = argv[1];
    const char *reference_host = argv[2];
    int num_samples = atoi(argv[3]);

    // Save configuration states to global registers for summary dump
    global_sample_host = sample_host;
    global_ref_host = reference_host;

    if (num_samples <= 0) {
        fprintf(stderr, "Error: Samples must be > 0\n");
        return EXIT_FAILURE;
    }

    struct sockaddr_in sample_addr, ref_addr;
    printf("Resolving domains...\n");
    if (resolve_dns(sample_host, &sample_addr) != 0 || resolve_dns(reference_host, &ref_addr) != 0) {
        return EXIT_FAILURE;
    }

    int sample_sock = socket(AF_INET, SOCK_DGRAM, 0);
    int ref_sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (sample_sock < 0 || ref_sock < 0) {
        perror("Socket creation failed");
        if (sample_sock >= 0) {
            close(sample_sock);
        }
        if (ref_sock >= 0) {
            close(ref_sock);
        }
        return EXIT_FAILURE;
    }

    // Set 1.5-second socket timeout
    struct timeval tv = {.tv_sec = 1, .tv_usec = 500000};
    setsockopt(sample_sock, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
    setsockopt(ref_sock, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

    // Register Ctrl+C interruption hook
    signal(SIGINT, handle_sigint);

    printf("Executing trace loop (%d samples). Press Ctrl+C to stop early:\n\n", num_samples);
    
    printf("%-5s | %-16s | %-15s | %-14s\n", "Step", "Offset Diff (s)", "Rolling Avg (s)", "Jitter (s)");
    printf("-----------------------------------------------------------------\n");

    double sum_drift = 0.0;
    double prev_drift = 0.0;
    double sum_jitter_dev = 0.0;
    int valid_samples = 0;

    // Loop runs while total count is under target and keep_running isn't cleared by Ctrl+C
    for (int i = 1; i <= num_samples && keep_running; i++) {
        double sample_offset = 0.0;
        double ref_offset = 0.0;

        int ret_s = get_ntp_offset_seconds(sample_sock, &sample_addr, &sample_offset, NULL);
        int ret_r = get_ntp_offset_seconds(ref_sock, &ref_addr, &ref_offset, NULL);

        if (ret_s != 0 || ret_r != 0) {
            printf("%-5d | %-16s | %-15s | %-14s\n", i, "ERROR/TIMEOUT", "N/A", "N/A");
            continue;
        }

        valid_samples++;
        global_valid_samples = valid_samples; // Synchronize to global space
        
        // Drift estimate is the difference between per-host NTP clock offsets.
        double current_drift = sample_offset - ref_offset;
        
        sum_drift += current_drift;
        global_sum_drift = sum_drift;
        
        double rolling_avg = sum_drift / valid_samples;

        double rolling_jitter = 0.0;
        if (valid_samples > 1) {
            double current_diff = fabs(current_drift - prev_drift);
            sum_jitter_dev += current_diff;
            global_sum_jitter_dev = sum_jitter_dev;
            rolling_jitter = sum_jitter_dev / (valid_samples - 1);
        }

        // CHANGED: Format specifiers modified to %+.6f to force 6 decimal places (microsecond resolution)
        printf("%-5d | %-+16.6f | %-+15.6f | %-14.6f\n", 
               i, current_drift, rolling_avg, rolling_jitter);
        fflush(stdout);

        prev_drift = current_drift;

        if (i < num_samples && keep_running) {
            // Anti-throttling responsive split loop (breaks quickly if Ctrl+C is pressed)
            for (int d = 0; d < 25 && keep_running; d++) {
                usleep(10000); 
            }
        }
    }

    close(sample_sock);
    close(ref_sock);

    // Final Summary Scorecard Implementation
    printf("\n\n-----------------------------------------------------------------\n");
    printf("                       FINAL DRIFT SUMMARY                       \n");
    printf("-----------------------------------------------------------------\n");
    printf("Sample Server Node:      %s\n", global_sample_host);
    printf("Reference Clock Source:  %s\n", global_ref_host);
    printf("Total Valid Traces:      %d\n", global_valid_samples);
    
    if (global_valid_samples > 0) {
        double final_avg = global_sum_drift / global_valid_samples;
        double final_jitter = (global_valid_samples > 1) ? (global_sum_jitter_dev / (global_valid_samples - 1)) : 0.0;
        printf("Final Average Drift:     %+.6f seconds\n", final_avg);
        printf("Final Mean Jitter:       %.6f seconds\n", final_jitter);
    } else {
        printf("Final Performance:       No successful samples captured.\n");
    }
    printf("-----------------------------------------------------------------\n");

    return EXIT_SUCCESS;
}
